### ISSUE TITLE
More of a Question about the Spicy Animations

### ISSUE THREAD

**Issue by reikitsune** [AlonWoof/SA1_Chars_Nude#1]
I'm currently playing with the mod on, and was wondering if the animations happen automatically at some point, or I trigger them with a input?

**Comment by AlonWoof** [comment]
Currently only the one with Sonic x Tails works, and you must stand *really* close to Tails.
It works best in places like the Casinopolis showers, and it's a rare chance.

In the update I might make it happen manually via a button input.
