### ISSUE TITLE
No way to toggle which characters are nude

### ISSUE THREAD

**Issue by Ehoh22** [AlonWoof/SA1_Chars_Nude#2]
With the original Dreamcast character pack you could toggle which characters got changed, I was wondering if you could do that here.

**Comment by AlonWoof** [comment]
No, I haven't implemented that feature, sorry. I feel like it would defeat the whole purpose of the mod if I did. 

But I will consider that option for the major rewrite I'm doing currently, thank you for your input.

**Comment by Ehoh22** [comment]
Thank you.
